apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Orders-V2
  description: The Doddle Orders API
  tags:
    - doddle
    - rest
spec:
  type: openapi
  lifecycle: production
  owner: luke.murphy@doddle.com
  definition:
    $text: https://github.com/jogabonitolm/backstage/blob/master/api-templates/examples/swagger/orders-v2-swagger.yaml
