openapi: "3.0.0"
info:
  title: Orders
  version: v2
servers:
  - url: https://apigw.eu-preprod.doddle.tech/v2
  - url: https://apigw.apac-preprod.doddle.tech/v2
components: 
  securitySchemes:
    OAuth2:
      type: oauth2
      flows: 
        clientCredentials: 
          tokenUrl: /v1/oauth/token
          scopes:
            orders:read: Grants read access
            orders:write: Grants write access
paths:
  /orders/:
    post:
      description: Submit an order to Doddle 
      security:
        - OAuth2:
          - orders:read
          - orders:write
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
  /orders/orderId/{orderId}:
    get:
      description: |
        Get an order by order id
      parameters:
        - description: The order uuid
          in: path
          name: orderId
          required: true
          schema:
              type: string
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
  /orders/externalorderid/{externalorderId}/companyId/{companyId}:
    get:
      description: |
        Get an order by order id
      parameters:
        - description: The retailer order id
          in: path
          name: externalorderId
          required: true
          schema:
              type: string
        - description: The company id
          in: path
          name: companyId
          required: true
          schema:
              type: string 
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
