swagger: '2.0'
schemes:
  - https
host: apigw.eu-preprod.doddle.tech
basePath: /v2
info:
  title: Orders
  version: v2
externalDocs:
  url: 'https://apigw.eu-preprod.doddle.tech'
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    tokenUrl: https://apigw.eu-preprod.doddle.tech/v1/oauth/token
    scopes:
      orders:read: Grants read access
      orders:write: Grants write access
paths:
  '/orders':
    post:
      description: |
       Submit an order to Doddle 
      consumes:
        - application/json 
      parameters:
        - description: The JSON request body
          in: body
          name: body
          required: true
          type: object        
      security:    
        - OAuth2: [orders:read, orders:write]  
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
  '/orders/orderId/{orderId}':
    get:
      description: |
        Get an order by order id
      parameters:
        - description: The order uuid
          in: path
          name: orderId
          required: true
          type: string
        - description: It is used to set specified media type.
          in: header
          name: Accept
          type: string
      security:    
        - OAuth2: [orders:read]  
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
  '/orders/externalorderid/{externalorderId}/companyId/{companyId}':
    get:
      description: |
        Get an order by order id
      parameters:
        - description: The retailer order id
          in: path
          name: externalorderId
          required: true
          type: string
        - description: The company id
          in: path
          name: companyId
          required: true
          type: string  
        - description: It is used to set specified media type.
          in: header
          name: Accept
          type: string
      security:    
        - OAuth2: [orders:read]  
      responses:
        '200':
          description: OK
        '429':
          description: |
            API rate limit exceeded.
definitions:
  Customer:          
    type: object
    required:
      - name
    properties:
      email:
        type: string
      mobileNumber:
        type: string
      name:
        type: object
        properties:
          firstName:
            type: string
          lastName:
            type: string
        required:
          - firstName
  OrderLines:
    type: array
    items: {}
  SourceLocation:
    type: array
    items:
      type: object
      properties:
        locationType:
          type: string
  DestinationLocation:
    type: object
    properties:
      locationType:
        type: string
